apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
  labels:
    app: react-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app1
  template:
    metadata:
      labels:
        app: react-app1
    spec:
      containers:
      - name: react-app1
        image: nakkumar/testreact:35
        ports:
        - containerPort: 8080
#        imagePullPolicy: Never
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: react-app1-service
spec:
  type: NodePort
  ports:
  - name: http
    port:  90
    targetPort: 8080
    protocol: TCP
  selector:
    app: react-app1
